notifications:
    email: false
dist: trusty
language: python
python: 2.7
services:
    - postgresql
addons:
    postgresql: "9.6"
cache: pip
before_install:  # copied from pgtest's travis.yml
    - sudo apt-get install locate
    - sudo updatedb
install:
    - pip install --upgrade pip
    - pip install git+https://github.com/aiidateam/aiida_core.git#egg=aiida_core
    - pip install -e .
    - pip install tox-travis
script: tox
